//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeStockC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Details_Livraison
    {
        public int ID_Livraison { get; set; }
        public int ID_Produit { get; set; }
        public string Quantite { get; set; }
        public int IdDetail { get; set; }
        public string Nom_Produit { get; set; }
    
        public virtual Livraison Livraison { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
