//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeStockC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livraison
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Livraison()
        {
            this.Details_Livraison = new HashSet<Details_Livraison>();
        }
    
        public int ID_Livraison { get; set; }
        public System.DateTime Date_Livraison { get; set; }
        public int ID_Client { get; set; }
        public string Fournisseur { get; set; }
        public string Num_Document { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Details_Livraison> Details_Livraison { get; set; }
    }
}
