//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeStockC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produit()
        {
            this.Affectations = new HashSet<Affectation>();
            this.Details_Commande = new HashSet<Details_Commande>();
            this.Details_Livraison = new HashSet<Details_Livraison>();
        }
    
        public int ID_Produit { get; set; }
        public string Nom_Produit { get; set; }
        public string Quantité_Produit { get; set; }
        public string Prix_Produit { get; set; }
        public byte[] Image_Produit { get; set; }
        public int ID_Categorie { get; set; }
        public int ID_Type { get; set; }
        public string Stock_Alerte { get; set; }
        public string Date_Controle { get; set; }
        public string NumInventaire { get; set; }
        public string N_Serie { get; set; }
        public string Tarif_Achat { get; set; }
        public string Poids { get; set; }
        public string Marge { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Affectation> Affectations { get; set; }
        public virtual Categorie Categorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Details_Commande> Details_Commande { get; set; }
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Details_Livraison> Details_Livraison { get; set; }
    }
}
